Merge tox + circleci into master.
CircleCI won't pick config from a branch, so I need to merge in my
master.
--
Squashed commit of the following:

commit b505798725b2d1bf3fc8c05bc8994659edd37f9f
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Tue Jun 4 09:27:35 2019 +0200

    Add CircleCI config

commit c8860d7c14f0b8a6d0ce273e2f53491c24d58db3
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Tue Jun 4 09:22:16 2019 +0200

    coverage working on tox

commit 4011c851de3cee17b7394104a4ad7ba9619ebed2
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:16:24 2019 +0200

    Add .eggs/ to .gitignore

commit fc68e3bba13376ed278f52d7dcbb368c954e9407
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:14:48 2019 +0200

    Refs #103, change pypi classifiers regarding python versions.

    This branch is assuming python3 only suppor (because we assume Django
    >=2.0), this we remove the python2 classifiers

commit 5f9084493d07fe50db321543fc40b29d49db9405
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:13:41 2019 +0200

    Properly set html_static_path in sphinx

    The directory pointed previously does not exist which raises a warning,
    which is an error on the test suite (warnings are treated as errors).

    There is not static folder for now, so we simply override the setting as
    appropiate.

commit 5fe3e0b37bae59d9b57053028329202346af0c72
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:13:28 2019 +0200

    Fix syntax error in docs/usage.rst

commit 222f513b3336cc80fa4efaef17acd3f408090de6
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:12:52 2019 +0200

    Fixes to tox.ini

    It now works, except for docs (next commit)
    Testing only python3 and Django 2.0 and 2.2

commit d20e8a4715725ab4df5a4585f0f5c249cdb088c6
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:12:07 2019 +0200

    Improve requirements-test.txt

    By removing things already in requirements.txt and then including
    requirements.txt on requirements-test.txt

commit cd40ae8333c3fecefd2234bd02bca8629db47d4e
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:10:51 2019 +0200

    Reorg dependencies.

    Dependencies both listed in setup.py and requirements.txt are removed
    from requirements.txt. The explicit versions of requirements.txt have
    been moved to the setup.py.

    This avoids duplicate dependencies, also will allow tox to override
    Django version on a later commit.

commit adafaa07359dd6f35f9c21c69b4cae9c76e79660
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 17:57:14 2019 +0200

    Fix indentation error in docs/installation.rst

commit 678a06c34dd51a1848d3759dca91156a837286aa
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 17:55:22 2019 +0200

    Force call to sys.exit() on run_tests

    Not calling sys.exit(), even with a 0 (ok) exit code, makes the function
    return None, which will make the runner crash on a successfull test run.

    ```python
    Traceback (most recent call last):
       ...
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 212, in loadTestsFromName
        (obj, test))
    TypeError: calling <function run_tests at 0x7f7fc472c1e0> returned None, not a test
    ```

    Calling sys.exit(failures) fixes this.

commit 6c61ec818ba721d7171f2d4c80c22e8a0bcdc8a6
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 13:11:48 2019 +0200

    Fix test_views which would never pass previously

    The previous code imported crud_views and tried to use an unexisting
    class from there (the file is currently empty).

    The test is now incomplete, but passes. A TODO note is added.

commit 8ffd335421b1ccde392769090aa41b26f38146ed
Author: Óscar M. Lage <info@oscarmlage.com>
Date:   Tue Apr 16 11:04:30 2019 +0200

    Fix (temporary) conflict with mixin and mymixin in NOCLASS that gives a metaclass TypeError that makes unusable the crud