Refactor of test infrastructure.
The test system now uses pytest with some useful plugins as I believe
pytest to be considerably easier to use than standard django test suite.
To run tests:

    pytest

We also enable Selenium for client side testing and to generate
screenshots. To test without selenium:

    pytest -m 'not selenium'

Pre-existing tests have been migrated and some other tests have been
added bringing the current coverage to 57% up from 39%. Note that
previous testing was prrety much a call to crud_for_app, the current
tests actually test for some of the functionality, though a lot is yet
to be written.

Also, what was now 'testapp' is now 'test_project' and
'test_project.testapp' to allow a) to use pytest-django and b) to make
it easier to further extend the testapp/test_project for more testing.

Last but not least, you can't use "python setup.py test" but have to go
with "pytest". That was to avoid another dependency on pytest-runner.
It's something to keep working.

Squashed commit of the following (only listing important ones):

commit 17f250b94ed2f1b98bead1b0f403d2ebcac03879
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Sun Jun 9 01:56:55 2019 +0200

    testapp.Author remove auto_now_add of birthday.

    It does not make sense because auto_now_add is not a default, but a
    total override. That is: the current date is always used on create.

commit 1666646469b777943f1623ca25f677232daf67ad
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Sat Jun 8 21:42:10 2019 +0200

    Introduce pytest

    We introduce pytest as we feel it more comfortable to write and run
    tests with. We add some development dependencies for it and include the
    necessary plugins.

    The current test suite now runs with pytest and it passes.

    Also, we introduce test_project to extend it with more stuff later down
    the road. The project is inserted into the python path with the
    pytest-pythonpath plugin.

    Introducing a plugin just to handle the python past is not something I'm
    particularly okay with, but it does the job for the moment.

    The pre-existing testapp is now inside the test_project.

commit db27099b06fd122742a1c10852f0adc3e4223ee2
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 18:13:41 2019 +0200

    Properly set html_static_path in sphinx

    The directory pointed previously does not exist which raises a warning,
    which is an error on the test suite (warnings are treated as errors).

    There is not static folder for now, so we simply override the setting as
    appropiate.

commit 2afe00f454fd4641df4f04fc08af44a59fe41645
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 17:55:22 2019 +0200

    Force call to sys.exit() on run_tests

    Not calling sys.exit(), even with a 0 (ok) exit code, makes the function
    return None, which will make the runner crash on a successfull test run.

    ```python
    Traceback (most recent call last):
       ...
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/home/marc/.pyenv/versions/3.7.3/lib/python3.7/unittest/loader.py", line 212, in loadTestsFromName
        (obj, test))
    TypeError: calling <function run_tests at 0x7f7fc472c1e0> returned None, not a test
    ```

    Calling sys.exit(failures) fixes this.

commit ca7fc3866f3827b149e09ad5f6beb28a2dcfdbc2
Author: Marc Fargas <telenieko@telenieko.com>
Date:   Mon Jun 3 13:11:48 2019 +0200

    Fix test_views which would never pass previously

    The previous code imported crud_views and tried to use an unexisting
    class from there (the file is currently empty).

    The test is now incomplete, but passes. A TODO note is added.